[2017/06/26 11:47:10][INFO](wrapper.py:90) order succeeded : {'order_id': 197405, 'limit': 0.0, 'amount': 1, 'received': 0.0, 'remains': 1.0, 'currency_pair': 'zaif_jpy', 'price': 0.2819, 'comment': '', 'action': 'ask'}
[2017/06/26 11:51:09][INFO](wrapper.py:90) order succeeded : {'amount': 1, 'currency_pair': 'zaif_jpy', 'action': 'ask', 'remains': 1.0, 'comment': '', 'received': 0.0, 'limit': 0.0, 'price': 1, 'order_id': 197411}
[2017/06/26 11:52:51][INFO](wrapper.py:90) order succeeded : {'received': 0.0, 'currency_pair': 'zaif_jpy', 'comment': '', 'remains': 1.0, 'action': 'ask', 'order_id': 197414, 'amount': 1, 'price': 1, 'limit': 0.0}
[2017/06/26 11:54:31][INFO](wrapper.py:90) order succeeded : {'received': 0.0, 'price': 1, 'comment': '', 'action': 'ask', 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'limit': 0.0, 'amount': 1, 'order_id': 197421}
[2017/06/26 11:55:43][INFO](wrapper.py:90) order succeeded : {'currency_pair': 'zaif_jpy', 'action': 'ask', 'remains': 1.0, 'received': 0.0, 'order_id': 197430, 'amount': 1, 'limit': 0.0, 'price': 1, 'comment': ''}
[2017/06/26 11:56:17][INFO](wrapper.py:90) order succeeded : {'price': 1, 'currency_pair': 'zaif_jpy', 'comment': '', 'action': 'ask', 'amount': 1, 'order_id': 197433, 'limit': 0.0, 'received': 0.0, 'remains': 1.0}
[2017/06/26 11:56:35][INFO](wrapper.py:90) order succeeded : {'remains': 1.0, 'comment': '', 'price': 1, 'limit': 0.0, 'order_id': 197436, 'currency_pair': 'zaif_jpy', 'action': 'ask', 'amount': 1, 'received': 0.0}
[2017/06/26 11:57:59][INFO](wrapper.py:90) order succeeded : {'limit': 0.0, 'action': 'ask', 'comment': '', 'currency_pair': 'zaif_jpy', 'order_id': 197442, 'received': 0.0, 'remains': 1.0, 'price': 1, 'amount': 1}
[2017/06/26 11:58:46][INFO](wrapper.py:90) order succeeded : {'action': 'ask', 'limit': 0.0, 'currency_pair': 'zaif_jpy', 'order_id': 197446, 'comment': '', 'remains': 1.0, 'amount': 1, 'received': 0.0, 'price': 1}
[2017/06/26 12:01:01][INFO](wrapper.py:90) order succeeded : {'price': 0.272, 'action': 'ask', 'amount': 1, 'remains': 0.0, 'currency_pair': 'zaif_jpy', 'received': 0.271728, 'comment': '', 'limit': 0.0, 'order_id': 0}
[2017/06/26 12:01:01][INFO](wrapper.py:90) order succeeded : {'price': 0.272, 'action': 'ask', 'amount': 1, 'remains': 0.0, 'currency_pair': 'zaif_jpy', 'received': 0.271728, 'comment': '', 'limit': 0.0, 'order_id': 0}
[2017/06/26 12:01:02][INFO](wrapper.py:90) order succeeded : {'price': 0.272, 'action': 'ask', 'amount': 1, 'remains': 0.0, 'currency_pair': 'zaif_jpy', 'received': 0.271728, 'comment': '', 'limit': 0.0, 'order_id': 0}
[2017/06/26 12:01:02][INFO](wrapper.py:90) order succeeded : {'price': 0.272, 'action': 'ask', 'amount': 1, 'remains': 0.0, 'currency_pair': 'zaif_jpy', 'received': 0.271728, 'comment': '', 'limit': 0.0, 'order_id': 0}
[2017/06/26 12:05:05][INFO](wrapper.py:90) order succeeded : {'remains': 1.0, 'currency_pair': 'zaif_jpy', 'limit': 0.0, 'amount': 1, 'comment': '', 'received': 0.0, 'order_id': 197469, 'price': 1, 'action': 'ask'}
[2017/06/26 12:05:40][INFO](wrapper.py:90) order succeeded : {'remains': 1.0, 'comment': '', 'amount': 1, 'action': 'ask', 'currency_pair': 'zaif_jpy', 'received': 0.0, 'price': 1, 'order_id': 197472, 'limit': 0.0}
[2017/06/26 12:06:05][INFO](wrapper.py:90) order succeeded : {'comment': '', 'amount': 1, 'received': 0.0, 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'limit': 0.0, 'action': 'ask', 'price': 1, 'order_id': 197474}
[2017/06/26 12:11:09][INFO](wrapper.py:90) order succeeded : {'limit': 0.0, 'amount': 1, 'currency_pair': 'zaif_jpy', 'order_id': 197486, 'comment': '', 'price': 1, 'remains': 1.0, 'action': 'ask', 'received': 0.0}
[2017/06/26 12:11:31][INFO](wrapper.py:90) order succeeded : {'action': 'ask', 'remains': 1.0, 'limit': 0.0, 'price': 1, 'order_id': 197488, 'comment': '', 'currency_pair': 'zaif_jpy', 'amount': 1, 'received': 0.0}
[2017/06/26 12:17:11][INFO](wrapper.py:90) order succeeded : {'action': 'ask', 'comment': '', 'order_id': 197497, 'received': 0.0, 'limit': 0.0, 'price': 1, 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'amount': 1}
[2017/06/26 12:17:11][ERROR](wrapper.py:31) cancel_order() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: cancel_order() takes 1 positional argument but 2 were given
[2017/06/26 12:17:16][ERROR](wrapper.py:31) cancel_order() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: cancel_order() takes 1 positional argument but 2 were given
[2017/06/26 12:17:21][ERROR](wrapper.py:31) cancel_order() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: cancel_order() takes 1 positional argument but 2 were given
[2017/06/26 12:17:26][ERROR](wrapper.py:31) cancel_order() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: cancel_order() takes 1 positional argument but 2 were given
[2017/06/26 12:17:31][ERROR](wrapper.py:31) cancel_order() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args
TypeError: cancel_order() takes 1 positional argument but 2 were given, **kwargs)
[2017/06/26 12:20:19][INFO](wrapper.py:90) order succeeded : {'currency_pair': 'zaif_jpy', 'order_id': 197507, 'limit': 0.0, 'amount': 1, 'received': 0.0, 'action': 'ask', 'remains': 1.0, 'comment': '', 'price': 1}
[2017/06/26 12:22:04][INFO](wrapper.py:90) order succeeded : {'action': 'ask', 'comment': '', 'price': 1, 'remains': 1.0, 'order_id': 197510, 'amount': 1, 'currency_pair': 'zaif_jpy', 'received': 0.0, 'limit': 0.0}
[2017/06/26 12:22:19][INFO](wrapper.py:90) order succeeded : {'price': 1, 'comment': '', 'received': 0.0, 'action': 'ask', 'order_id': 197513, 'amount': 1, 'remains': 1.0, 'limit': 0.0, 'currency_pair': 'zaif_jpy'}
[2017/06/26 12:22:36][INFO](wrapper.py:90) order succeeded : {'currency_pair': 'zaif_jpy', 'remains': 1.0, 'amount': 1, 'comment': '', 'received': 0.0, 'price': 1, 'limit': 0.0, 'order_id': 197515, 'action': 'ask'}
[2017/06/26 12:22:36][ERROR](wrapper.py:31) {"order_id": ["required field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["required field"]}
[2017/06/26 12:22:41][ERROR](wrapper.py:31) {"order_id": ["required field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["required field"]}
[2017/06/26 12:22:46][ERROR](wrapper.py:31) {"order_id": ["required field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["required field"]}
[2017/06/26 12:22:51][ERROR](wrapper.py:31) {"order_id": ["required field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["required field"]}
[2017/06/26 12:22:56][ERROR](wrapper.py:31) {"order_id": ["required field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["required field"]}
[2017/06/26 12:23:37][INFO](wrapper.py:90) order succeeded : {'action': 'ask', 'remains': 1.0, 'limit': 0.0, 'price': 1, 'comment': '', 'amount': 1, 'currency_pair': 'zaif_jpy', 'order_id': 197520, 'received': 0.0}
[2017/06/26 12:23:37][ERROR](wrapper.py:31) cancel_order() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: cancel_order() takes 1 positional argument but 2 were given
[2017/06/26 12:23:42][ERROR](wrapper.py:31) cancel_order() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: cancel_order() takes 1 positional argument but 2 were given
[2017/06/26 12:24:45][INFO](wrapper.py:90) order succeeded : {'remains': 1.0, 'order_id': 197526, 'action': 'ask', 'currency_pair': 'zaif_jpy', 'limit': 0.0, 'amount': 1, 'price': 1, 'received': 0.0, 'comment': ''}
[2017/06/26 12:24:46][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:26:30][INFO](wrapper.py:90) order succeeded : {'order_id': 197537, 'price': 1, 'currency_pair': 'zaif_jpy', 'limit': 0.0, 'received': 0.0, 'amount': 1, 'comment': '', 'action': 'ask', 'remains': 1.0}
[2017/06/26 12:26:31][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:26:53][INFO](wrapper.py:90) order succeeded : {'order_id': 197540, 'amount': 1, 'remains': 1.0, 'received': 0.0, 'comment': '', 'currency_pair': 'zaif_jpy', 'action': 'ask', 'price': 1, 'limit': 0.0}
[2017/06/26 12:26:53][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:27:34][INFO](wrapper.py:90) order succeeded : {'remains': 1.0, 'action': 'ask', 'currency_pair': 'zaif_jpy', 'price': 1, 'order_id': 197546, 'limit': 0.0, 'received': 0.0, 'comment': '', 'amount': 1}
[2017/06/26 12:27:34][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 12:27:39][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 12:27:44][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 12:27:49][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 12:27:54][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 12:28:26][INFO](wrapper.py:90) order succeeded : {'order_id': 197550, 'action': 'ask', 'limit': 0.0, 'comment': '', 'currency_pair': 'zaif_jpy', 'amount': 1, 'price': 1, 'remains': 1.0, 'received': 0.0}
[2017/06/26 12:28:26][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:28:41][INFO](wrapper.py:90) order succeeded : {'remains': 1.0, 'order_id': 197552, 'amount': 1, 'limit': 0.0, 'comment': '', 'received': 0.0, 'action': 'ask', 'price': 1, 'currency_pair': 'zaif_jpy'}
[2017/06/26 12:28:41][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 12:28:46][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 12:28:51][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 12:29:43][INFO](wrapper.py:90) order succeeded : {'comment': '', 'price': 1, 'received': 0.0, 'action': 'ask', 'limit': 0.0, 'amount': 1, 'remains': 1.0, 'order_id': 197554, 'currency_pair': 'zaif_jpy'}
[2017/06/26 12:29:43][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:30:56][INFO](wrapper.py:91) order succeeded : {'order_id': 197558, 'currency_pair': 'zaif_jpy', 'comment': '', 'limit': 0.0, 'price': 1, 'action': 'ask', 'amount': 1, 'remains': 1.0, 'received': 0.0}
[2017/06/26 12:30:56][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:32:12][INFO](wrapper.py:91) order succeeded : {'remains': 1.0, 'order_id': 197566, 'currency_pair': 'zaif_jpy', 'received': 0.0, 'comment': '', 'action': 'ask', 'limit': 0.0, 'price': 1, 'amount': 1}
[2017/06/26 12:32:27][INFO](wrapper.py:91) order succeeded : {'comment': '', 'price': 1, 'action': 'ask', 'amount': 1, 'remains': 1.0, 'received': 0.0, 'currency_pair': 'zaif_jpy', 'order_id': 197567, 'limit': 0.0}
[2017/06/26 12:32:27][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:33:03][INFO](wrapper.py:91) order succeeded : {'action': 'ask', 'price': 1, 'limit': 0.0, 'order_id': 197570, 'currency_pair': 'zaif_jpy', 'amount': 1, 'remains': 1.0, 'received': 0.0, 'comment': ''}
[2017/06/26 12:33:06][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:33:34][INFO](wrapper.py:91) order succeeded : {'price': 1, 'amount': 1, 'comment': '', 'received': 0.0, 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'limit': 0.0, 'order_id': 197571, 'action': 'ask'}
[2017/06/26 12:33:44][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:34:03][INFO](wrapper.py:91) order succeeded : {'comment': '', 'amount': 1, 'action': 'ask', 'order_id': 197574, 'received': 0.0, 'remains': 1.0, 'currency_pair': 'zaif_jpy', 'limit': 0.0, 'price': 1}
[2017/06/26 12:34:05][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:34:45][INFO](wrapper.py:91) order succeeded : {'order_id': 197579, 'remains': 1.0, 'price': 1, 'action': 'ask', 'comment': '', 'currency_pair': 'zaif_jpy', 'amount': 1, 'limit': 0.0, 'received': 0.0}
[2017/06/26 12:34:46][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:35:04][INFO](wrapper.py:91) order succeeded : {'amount': 1, 'received': 0.0, 'order_id': 197580, 'limit': 0.0, 'remains': 1.0, 'action': 'ask', 'price': 1, 'currency_pair': 'zaif_jpy', 'comment': ''}
[2017/06/26 12:35:05][ERROR](wrapper.py:23) invalid currency_pair parameter
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 48, in active_orders
    return super().active_orders(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 242, in active_orders
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: invalid currency_pair parameter
[2017/06/26 12:37:08][ERROR](wrapper.py:31) active_orders() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: active_orders() takes 1 positional argument but 2 were given
[2017/06/26 12:37:13][ERROR](wrapper.py:31) active_orders() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: active_orders() takes 1 positional argument but 2 were given
[2017/06/26 12:37:18][ERROR](wrapper.py:31) active_orders() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: active_orders() takes 1 positional argument but 2 were given
[2017/06/26 12:37:23][ERROR](wrapper.py:31) active_orders() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: active_orders() takes 1 positional argument but 2 were given
[2017/06/26 12:37:28][ERROR](wrapper.py:31) active_orders() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: active_orders() takes 1 positional argument but 2 were given
[2017/06/26 12:38:17][ERROR](wrapper.py:31) active_orders() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
TypeError: active_orders() takes 1 positional argument but 2 were given
[2017/06/26 12:38:28][INFO](wrapper.py:91) order succeeded : {'comment': '', 'amount': 1, 'remains': 1.0, 'action': 'ask', 'received': 0.0, 'price': 1, 'currency_pair': 'zaif_jpy', 'limit': 0.0, 'order_id': 197585}
[2017/06/26 12:38:29][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:39:05][INFO](wrapper.py:91) order succeeded : {'limit': 0.0, 'amount': 1, 'comment': '', 'price': 1, 'remains': 1.0, 'action': 'ask', 'order_id': 197592, 'received': 0.0, 'currency_pair': 'zaif_jpy'}
[2017/06/26 12:39:07][ERROR](wrapper.py:31) {"currency_pair": ["unknown field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"currency_pair": ["unknown field"]}
[2017/06/26 12:39:12][ERROR](wrapper.py:31) {"currency_pair": ["unknown field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"currency_pair": ["unknown field"]}
[2017/06/26 12:39:17][ERROR](wrapper.py:31) {"currency_pair": ["unknown field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"currency_pair": ["unknown field"]}
[2017/06/26 12:39:22][ERROR](wrapper.py:31) {"currency_pair": ["unknown field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"currency_pair": ["unknown field"]}
[2017/06/26 12:39:27][ERROR](wrapper.py:31) {"currency_pair": ["unknown field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"currency_pair": ["unknown field"]}
[2017/06/26 12:40:04][INFO](wrapper.py:91) order succeeded : {'limit': 0.0, 'received': 0.0, 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'order_id': 197603, 'action': 'ask', 'price': 1, 'amount': 1, 'comment': ''}
[2017/06/26 12:40:05][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:40:53][INFO](wrapper.py:90) order succeeded : {'remains': 1.0, 'price': 1, 'order_id': 197607, 'amount': 1, 'received': 0.0, 'currency_pair': 'zaif_jpy', 'comment': '', 'action': 'ask', 'limit': 0.0}
[2017/06/26 12:40:54][ERROR](wrapper.py:31) {"currency_pair": ["unknown field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"currency_pair": ["unknown field"]}
[2017/06/26 12:40:59][ERROR](wrapper.py:31) {"currency_pair": ["unknown field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"currency_pair": ["unknown field"]}
[2017/06/26 12:41:04][ERROR](wrapper.py:31) {"currency_pair": ["unknown field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"currency_pair": ["unknown field"]}
[2017/06/26 12:41:09][ERROR](wrapper.py:31) {"currency_pair": ["unknown field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"currency_pair": ["unknown field"]}
[2017/06/26 12:41:14][ERROR](wrapper.py:31) {"currency_pair": ["unknown field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"currency_pair": ["unknown field"]}
[2017/06/26 12:41:54][INFO](wrapper.py:90) order succeeded : {'currency_pair': 'zaif_jpy', 'received': 0.0, 'action': 'ask', 'price': 1, 'order_id': 197611, 'comment': '', 'remains': 1.0, 'limit': 0.0, 'amount': 1}
[2017/06/26 12:41:55][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 52, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:42:36][INFO](wrapper.py:91) order succeeded : {'currency_pair': 'zaif_jpy', 'received': 0.0, 'limit': 0.0, 'price': 1, 'amount': 1, 'action': 'ask', 'remains': 1.0, 'order_id': 197613, 'comment': ''}
[2017/06/26 12:42:37][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 12:43:41][INFO](wrapper.py:91) order succeeded : {'limit': 0.0, 'price': 1, 'order_id': 197618, 'amount': 1, 'received': 0.0, 'comment': '', 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'action': 'ask'}
[2017/06/26 12:43:42][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 13:10:23][INFO](wrapper.py:91) order succeeded : {'received': 0.0, 'amount': 1, 'price': 1, 'currency_pair': 'zaif_jpy', 'order_id': 197661, 'limit': 0.0, 'action': 'ask', 'remains': 1.0, 'comment': ''}
[2017/06/26 13:10:24][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 13:11:03][INFO](wrapper.py:91) order succeeded : {'amount': 1, 'limit': 0.0, 'remains': 1.0, 'comment': '', 'currency_pair': 'zaif_jpy', 'received': 0.0, 'action': 'ask', 'order_id': 197667, 'price': 1}
[2017/06/26 13:11:24][INFO](wrapper.py:91) order succeeded : {'action': 'ask', 'price': 1, 'received': 0.0, 'order_id': 197668, 'limit': 0.0, 'amount': 1, 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'comment': ''}
[2017/06/26 13:11:25][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 13:12:18][INFO](wrapper.py:91) order succeeded : {'price': 1, 'limit': 0.0, 'received': 0.0, 'action': 'ask', 'currency_pair': 'zaif_jpy', 'order_id': 197678, 'remains': 1.0, 'comment': '', 'amount': 1}
[2017/06/26 13:12:19][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 13:13:35][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 13:13:51][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:13:56][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:14:01][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:14:06][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:14:11][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:14:56][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:15:01][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:15:06][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:15:11][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:15:16][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:17:41][INFO](wrapper.py:91) order succeeded : {'comment': '', 'limit': 0.0, 'amount': 1, 'currency_pair': 'xem_jpy', 'received': 20.2798998, 'order_id': 0, 'action': 'ask', 'remains': 0.0, 'price': 10}
[2017/06/26 13:17:41][ERROR](wrapper.py:31) {"order_id": ["must be of integer type"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["must be of integer type"]}
[2017/06/26 13:18:55][INFO](wrapper.py:91) order succeeded : {'remains': 1.0, 'order_id': 220336569, 'amount': 1, 'price': 40, 'action': 'ask', 'currency_pair': 'xem_jpy', 'comment': '', 'received': 0.0, 'limit': 0.0}
[2017/06/26 13:21:26][INFO](wrapper.py:91) order succeeded : {'action': 'ask', 'limit': 0.0, 'order_id': 197714, 'price': 2, 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'received': 0.0, 'comment': '', 'amount': 1}
[2017/06/26 13:21:26][ERROR](wrapper.py:31) {"order_id": ["required field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["required field"]}
[2017/06/26 13:21:31][ERROR](wrapper.py:31) {"order_id": ["required field"]}
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 214, in _execute_api
    params = self.params_pre_processing(schema_keys, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 106, in params_pre_processing
    self._validate(schema, params)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 128, in _validate
    raise Exception(json.dumps(v.errors))
Exception: {"order_id": ["required field"]}
[2017/06/26 13:21:43][INFO](wrapper.py:91) order succeeded : {'remains': 1.0, 'action': 'ask', 'limit': 0.0, 'price': 2, 'comment': '', 'amount': 1, 'currency_pair': 'zaif_jpy', 'order_id': 197716, 'received': 0.0}
[2017/06/26 13:22:07][INFO](wrapper.py:91) order succeeded : {'received': 0.0, 'amount': 1, 'action': 'ask', 'comment': '', 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'order_id': 197718, 'limit': 0.0, 'price': 2}
[2017/06/26 13:23:07][INFO](wrapper.py:91) order succeeded : {'currency_pair': 'zaif_jpy', 'action': 'ask', 'amount': 1, 'remains': 1.0, 'order_id': 197721, 'price': 2, 'limit': 0.0, 'comment': '', 'received': 0.0}
[2017/06/26 13:23:31][INFO](wrapper.py:91) order succeeded : {'currency_pair': 'zaif_jpy', 'action': 'ask', 'amount': 1, 'comment': '', 'limit': 0.0, 'received': 0.0, 'order_id': 197723, 'price': 2, 'remains': 1.0}
[2017/06/26 13:24:48][INFO](wrapper.py:91) order succeeded : {'comment': '', 'order_id': 197724, 'limit': 0.0, 'price': 2, 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'received': 0.0, 'action': 'ask', 'amount': 1}
[2017/06/26 13:27:38][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 13:27:54][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 13:28:05][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 13:28:16][ERROR](wrapper.py:23) order not found
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order not found
[2017/06/26 13:34:12][INFO](wrapper.py:91) order succeeded : {'action': 'ask', 'currency_pair': 'zaif_jpy', 'received': 0.0, 'remains': 1.0, 'price': 1, 'order_id': 197735, 'limit': 0.0, 'comment': '', 'amount': 1}
[2017/06/26 13:34:12][ERROR](wrapper.py:23) order is too new
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: order is too new
[2017/06/26 13:34:29][INFO](wrapper.py:91) order succeeded : {'amount': 1, 'received': 0.0, 'action': 'ask', 'price': 1, 'currency_pair': 'zaif_jpy', 'limit': 0.0, 'order_id': 197737, 'remains': 1.0, 'comment': ''}
[2017/06/26 13:35:22][INFO](wrapper.py:91) order succeeded : {'remains': 0.0, 'order_id': 0, 'received': 608.393997, 'currency_pair': 'xem_jpy', 'amount': 30, 'limit': 0.0, 'action': 'ask', 'comment': '', 'price': 1}
[2017/06/26 13:35:26][ERROR](wrapper.py:23) invalid order_id parameter
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 53, in cancel_order
    return super().cancel_order(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 260, in cancel_order
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: invalid order_id parameter
[2017/06/26 13:36:28][INFO](wrapper.py:91) order succeeded : {'action': 'ask', 'order_id': 220340413, 'price': 30, 'currency_pair': 'xem_jpy', 'received': 0.0, 'comment': '', 'limit': 0.0, 'amount': 1, 'remains': 1.0}
[2017/06/26 13:36:50][INFO](wrapper.py:91) order succeeded : {'price': 30, 'limit': 0.0, 'remains': 1.0, 'comment': '', 'action': 'ask', 'amount': 1, 'currency_pair': 'xem_jpy', 'received': 0.0, 'order_id': 220340479}
[2017/06/26 15:12:15][INFO](wrapper.py:90) order succeeded : {'price': 30, 'limit': 0.0, 'remains': 1.0, 'comment': '', 'order_id': 220360585, 'amount': 1, 'currency_pair': 'xem_jpy', 'received': 0.0, 'action': 'ask'}
[2017/06/26 15:30:48][ERROR](wrapper.py:32) __init__() missing 1 required positional argument: 'message'
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 50, in active_orders
    raise ZaifApiError
TypeError: __init__() missing 1 required positional argument: 'message'
[2017/06/26 15:30:53][ERROR](wrapper.py:32) __init__() missing 1 required positional argument: 'message'
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 50, in active_orders
    raise ZaifApiError
TypeError: __init__() missing 1 required positional argument: 'message'
[2017/06/26 15:30:58][ERROR](wrapper.py:32) __init__() missing 1 required positional argument: 'message'
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 50, in active_orders
    raise ZaifApiError
TypeError: __init__() missing 1 required positional argument: 'message'
[2017/06/26 15:31:03][ERROR](wrapper.py:32) __init__() missing 1 required positional argument: 'message'
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 50, in active_orders
    raise ZaifApiError
TypeError: __init__() missing 1 required positional argument: 'message'
[2017/06/26 15:31:08][ERROR](wrapper.py:32) __init__() missing 1 required positional argument: 'message'
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 50, in active_orders
    raise ZaifApiError
TypeError: __init__() missing 1 required positional argument: 'message'
[2017/06/26 15:31:27][ERROR](wrapper.py:23) test
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 50, in active_orders
    raise ZaifApiError('test')
zaifapi.api_error.ZaifApiError: test
[2017/06/26 15:32:02][ERROR](wrapper.py:23) test
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 49, in active_orders
    raise ZaifApiError('test')
zaifapi.api_error.ZaifApiError: test
[2017/06/26 15:32:02][ERROR](wrapper.py:23) test
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 49, in active_orders
    raise ZaifApiError('test')
zaifapi.api_error.ZaifApiError: test
[2017/06/26 15:32:02][ERROR](wrapper.py:23) test
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 49, in active_orders
    raise ZaifApiError('test')
zaifapi.api_error.ZaifApiError: test
[2017/06/26 15:32:02][ERROR](wrapper.py:23) test
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 49, in active_orders
    raise ZaifApiError('test')
zaifapi.api_error.ZaifApiError: test
[2017/06/26 15:32:02][ERROR](wrapper.py:23) test
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 49, in active_orders
    raise ZaifApiError('test')
zaifapi.api_error.ZaifApiError: test
[2017/06/26 15:32:26][ERROR](wrapper.py:23) test
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 50, in active_orders
    raise ZaifApiError('test')
zaifapi.api_error.ZaifApiError: test
[2017/06/26 16:38:39][ERROR](test.py:34) cda17178-7c0b-43db-adb2-ccebb427842a
NoneType: None
[2017/06/26 18:30:02][INFO](wrapper.py:90) order succeeded : {'comment': '', 'amount': 1, 'received': 1.0, 'price': 2, 'currency_pair': 'zaif_jpy', 'order_id': 0, 'limit': 0.0, 'action': 'bid', 'remains': 0.0}
[2017/06/26 18:31:30][INFO](wrapper.py:90) order succeeded : {'currency_pair': 'zaif_jpy', 'limit': 0.0, 'comment': '', 'received': 0.0, 'order_id': 198258, 'price': 0.1, 'amount': 1, 'action': 'bid', 'remains': 1.0}
[2017/06/26 18:32:24][INFO](wrapper.py:90) order succeeded : {'remains': 1.0, 'action': 'bid', 'comment': '', 'limit': 0.0, 'amount': 1, 'received': 0.0, 'price': 0.1, 'currency_pair': 'zaif_jpy', 'order_id': 198268}
[2017/06/26 18:34:03][INFO](wrapper.py:90) order succeeded : {'action': 'bid', 'received': 0.0, 'currency_pair': 'zaif_jpy', 'price': 0.1, 'amount': 1, 'order_id': 198284, 'limit': 0.0, 'comment': '', 'remains': 1.0}
[2017/06/26 18:34:49][INFO](wrapper.py:90) order succeeded : {'amount': 1, 'comment': '', 'action': 'bid', 'order_id': 198288, 'currency_pair': 'zaif_jpy', 'received': 0.0, 'remains': 1.0, 'limit': 0.0, 'price': 0.1}
[2017/06/26 18:36:32][INFO](wrapper.py:90) order succeeded : {'price': 0.1, 'order_id': 198300, 'action': 'bid', 'received': 0.0, 'amount': 1, 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'limit': 0.0, 'comment': ''}
[2017/06/26 18:36:48][INFO](wrapper.py:90) order succeeded : {'action': 'bid', 'currency_pair': 'zaif_jpy', 'order_id': 198302, 'limit': 0.0, 'price': 0.1, 'received': 0.0, 'amount': 1, 'comment': '', 'remains': 1.0}
[2017/06/26 18:37:20][INFO](wrapper.py:90) order succeeded : {'limit': 0.0, 'remains': 1.0, 'amount': 1, 'received': 0.0, 'action': 'bid', 'order_id': 198305, 'currency_pair': 'zaif_jpy', 'price': 0.1, 'comment': ''}
[2017/06/26 18:38:12][INFO](wrapper.py:90) order succeeded : {'amount': 1, 'received': 0.0, 'order_id': 198307, 'remains': 1.0, 'currency_pair': 'zaif_jpy', 'price': 0.1, 'limit': 0.0, 'action': 'bid', 'comment': ''}
[2017/06/26 18:38:23][INFO](wrapper.py:90) order succeeded : {'received': 0.0, 'limit': 0.0, 'price': 0.1, 'order_id': 198309, 'action': 'bid', 'currency_pair': 'zaif_jpy', 'comment': '', 'remains': 1.0, 'amount': 1}
[2017/06/26 18:39:43][INFO](wrapper.py:90) order succeeded : {'currency_pair': 'zaif_jpy', 'action': 'bid', 'order_id': 198310, 'amount': 1, 'comment': '', 'limit': 0.0, 'received': 0.0, 'remains': 1.0, 'price': 0.1}
[2017/06/26 18:40:54][INFO](wrapper.py:90) order succeeded : {'action': 'bid', 'order_id': 198313, 'remains': 1.0, 'received': 0.0, 'currency_pair': 'zaif_jpy', 'amount': 1, 'price': 0.1, 'limit': 0.0, 'comment': ''}
[2017/06/26 18:41:54][INFO](wrapper.py:90) order succeeded : {'comment': '', 'received': 0.0, 'action': 'bid', 'price': 0.1, 'order_id': 198318, 'currency_pair': 'zaif_jpy', 'limit': 0.0, 'remains': 1.0, 'amount': 1}
[2017/06/26 18:42:46][ERROR](wrapper.py:23) insufficient funds
Traceback (most recent call last):
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 21, in _wrapper
    return func(self, *args, **kwargs)
  File "c:\users\dshir\desktop\pycharm\zaif\zaifbot\zaifbot\api\wrapper.py", line 80, in trade
    ret = super().trade(**kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 264, in trade
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "C:\Users\dshir\desktop\Pycharm\zaif\lib\site-packages\zaifapi\impl.py", line 221, in _execute_api
    raise ZaifApiError(res['error'])
zaifapi.api_error.ZaifApiError: insufficient funds
[2017/06/26 18:43:24][INFO](wrapper.py:90) order succeeded : {'amount': 1, 'received': 0.0, 'price': 2, 'remains': 1.0, 'limit': 0.0, 'order_id': 198320, 'comment': '', 'action': 'ask', 'currency_pair': 'zaif_jpy'}
[2017/06/26 18:44:48][INFO](wrapper.py:90) order succeeded : {'action': 'ask', 'amount': 1, 'order_id': 198323, 'received': 0.0, 'comment': '', 'price': 2, 'limit': 0.0, 'currency_pair': 'zaif_jpy', 'remains': 1.0}
[2017/06/26 18:45:20][INFO](wrapper.py:90) order succeeded : {'price': 2, 'remains': 1.0, 'action': 'ask', 'currency_pair': 'zaif_jpy', 'limit': 0.0, 'amount': 1, 'order_id': 198325, 'received': 0.0, 'comment': ''}
[2017/06/26 18:46:28][INFO](wrapper.py:90) order succeeded : {'received': 0.0, 'amount': 1, 'comment': '', 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'limit': 0.0, 'price': 2, 'order_id': 198327, 'action': 'ask'}
[2017/06/26 18:47:18][INFO](wrapper.py:90) order succeeded : {'limit': 0.0, 'action': 'ask', 'remains': 1.0, 'price': 2, 'currency_pair': 'zaif_jpy', 'order_id': 198328, 'received': 0.0, 'comment': '', 'amount': 1}
[2017/06/26 18:47:34][INFO](wrapper.py:90) order succeeded : {'remains': 1.0, 'order_id': 198329, 'limit': 0.0, 'currency_pair': 'zaif_jpy', 'price': 2, 'action': 'ask', 'received': 0.0, 'comment': '', 'amount': 1}
[2017/06/26 18:48:32][INFO](wrapper.py:90) order succeeded : {'action': 'ask', 'amount': 1, 'remains': 1.0, 'limit': 0.0, 'currency_pair': 'zaif_jpy', 'price': 2, 'received': 0.0, 'order_id': 198333, 'comment': ''}
[2017/06/26 18:51:35][INFO](wrapper.py:90) order succeeded : {'price': 2, 'amount': 1, 'comment': '', 'order_id': 198351, 'currency_pair': 'zaif_jpy', 'action': 'ask', 'received': 0.0, 'remains': 1.0, 'limit': 0.0}
[2017/06/26 18:51:43][INFO](wrapper.py:90) order succeeded : {'amount': 1, 'currency_pair': 'zaif_jpy', 'price': 2, 'limit': 0.0, 'order_id': 198353, 'remains': 1.0, 'comment': '', 'action': 'ask', 'received': 0.0}
[2017/06/26 18:53:54][INFO](wrapper.py:90) order succeeded : {'limit': 0.0, 'currency_pair': 'zaif_jpy', 'remains': 1.0, 'amount': 1, 'price': 2, 'received': 0.0, 'action': 'ask', 'order_id': 198358, 'comment': ''}
